version: '3'
services:
  jenkins:
    build: ./jenkins
    ports: 
      - "8080:8080"
    volumes:
      - "jenkins_home:/ksemin/data/jenkins_home"
  app1:
    build: ./app1
    ports:
      - "5001:5000"
  app2:
    build: ./app2
    ports:
      - "5002:5000"
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
      - jenkins
volumes:
  jenkins_home:
